import json

# 150 Hand-Labelled Benchmark Test Cases covering all 6 intents & edge cases
categories_data = {
    "account_access": [
        ("I got locked out of my Apple ID and two-factor authentication is sending codes to my old lost phone number!", True),
        ("How do I change my Apple ID password from my iPad settings?", False),
        ("Cannot sign in to my Apple ID on my new MacBook Air after macOS update.", False),
        ("My account was disabled for security reasons, how can I unlock it?", True),
        ("I forgot my Apple ID passcode and my phone is completely unavailable.", True),
        ("How do I add a recovery contact to my Apple account?", False),
        ("I received an email saying my Apple ID was accessed from another country!", True),
        ("Where can I see which devices are signed in with my Apple ID?", False),
        ("Two-factor authentication codes are not arriving on my trusted phone.", True),
        ("How do I remove an old device from my Apple ID account list?", False),
        ("My Apple ID email address needs to be changed. Where do I go?", False),
        ("I am stuck in an activation lock screen on my refurbished iPhone.", True),
        ("Is it possible to merge two separate Apple ID accounts into one?", False),
        ("My security questions are not working when I try to reset my password.", True),
        ("How to set up Family Sharing for Apple ID accounts?", False),
        ("I can't turn off Find My iPhone because I forgot my Apple ID password.", True),
        ("How do I update my trusted phone number for security verification?", False),
        ("App Store keeps asking for my Apple ID password repeatedly every minute.", False),
        ("My child's Apple ID account is locked and cannot download apps.", True),
        ("How do I revoke app-specific passwords generated for third-party apps?", False),
        ("I think my Apple ID has been hacked because there are unknown app downloads.", True),
        ("Where do I manage my passkeys on iOS 17?", False),
        ("How do I generate a recovery key for my Apple account?", False),
        ("I cannot sign in to iCloud on Windows due to verification error.", False),
        ("Account recovery is taking more than 24 hours, can someone expedite this?", True)
    ],
    "billing_subscription": [
        ("I was charged $99.99 for an annual subscription I canceled during the trial period! I want my money back!", True),
        ("Where can I view my active App Store subscriptions on iOS 17?", False),
        ("Unauthorized charge of $14.99 on my credit card from iTunes this morning.", True),
        ("How do I change my payment method on file for my Apple ID?", False),
        ("My card was declined when renewing my iCloud storage plan.", False),
        ("I got charged twice for the same app purchase today. Refund please!", True),
        ("How can I request a refund for an accidentally purchased app?", True),
        ("Why does my billing invoice show pending status for 3 days?", False),
        ("How do I cancel my Apple Music individual subscription?", False),
        ("I see an unknown charge titled 'APL*APPLE COM/BILL' on my bank statement.", True),
        ("Can I transfer my App Store balance to another Apple ID account?", False),
        ("How do I redeem an App Store gift card on my iPhone?", False),
        ("I paid for 200GB iCloud storage but my account still says 5GB free.", False),
        ("My subscription auto-renewed without sending a reminder email.", True),
        ("How to download past tax invoices for my business Apple purchases?", False),
        ("I was charged for Apple Arcade even though I turned off auto-renew.", True),
        ("Where do I check my Apple ID gift card account balance?", False),
        ("My family member bought an in-app item without my permission.", True),
        ("How to update my credit card billing address on the App Store?", False),
        ("I want to turn off auto-renewal for my Apple One subscription bundle.", False),
        ("Why am I being charged sales tax on my digital app purchases?", False),
        ("My refund request was denied by the automated tool. Need human agent!", True),
        ("How do I share my Apple One subscription with family members?", False),
        ("Where can I view my complete order history for hardware items?", False),
        ("My payment keeps failing despite having sufficient balance.", False)
    ],
    "device_hardware": [
        ("My iPhone 15 Pro screen completely went green and flickers after dropping it on carpet.", True),
        ("What is the official battery replacement cost for an iPhone 13?", False),
        ("Speaker output sounds distorted and quiet on right side of my iPad Pro.", False),
        ("My iPhone battery health dropped from 100% to 85% in two months.", False),
        ("The back glass on my iPhone cracked. Is this covered under AppleCare+?", True),
        ("My camera lens has dust inside it causing spots on photos.", True),
        ("My MacBook Air keyboard keys are sticking and not registering presses.", True),
        ("The power button on my iPad mini feels loose and unresponsive.", True),
        ("My iPhone gets extremely hot to touch while charging on MagSafe.", False),
        ("Microphone is not picking up my voice during phone calls.", False),
        ("How do I check if my device is still under official Apple warranty?", False),
        ("My Apple Watch screen popped off near the edges.", True),
        ("Face ID stopped working and says 'a problem was detected with TrueDepth camera'.", True),
        ("My iPhone vibrates randomly even when there are no notifications.", False),
        ("Is water damage covered under the standard one-year limited warranty?", False),
        ("My MagSafe charger gets warm. Is that normal behaviour?", False),
        ("The charging port on my iPhone 12 feels loose and drops connection.", True),
        ("My Mac screen has dead pixels right in the middle.", True),
        ("How much does it cost to replace a lost AirPods Pro charging case?", False),
        ("My iPhone display has a faint burn-in image visible on white backgrounds.", True),
        ("My Apple Pencil is not charging when magnetically attached to iPad.", False),
        ("The touch screen stops responding to touch on the bottom half.", True),
        ("Does Apple Store provide walk-in hardware repairs without appointment?", False),
        ("My MacBook fan is spinning at maximum speed constantly.", False),
        ("The mute switch on the side of my iPhone feels broken.", True)
    ],
    "software_update": [
        ("iOS update gets stuck on 'Preparing Update...' for 3 hours. How to clear cache?", False),
        ("iPhone restarts randomly after installing the latest iOS beta release.", False),
        ("My battery drains rapidly after updating to the latest iOS release.", False),
        ("How do I opt out of the Apple Developer Beta profile on my phone?", False),
        ("System data storage taking up 50GB space after installing software update.", False),
        ("App Store crashes instantly every time I try to open it after update.", False),
        ("My apps fail to download and stay stuck on 'Waiting...' phase.", False),
        ("How do I roll back from iOS 18 beta to iOS 17 public release?", False),
        ("My phone gets stuck on the Apple logo loop during software update.", True),
        ("iMessage is not working properly after installing macOS update.", False),
        ("How do I enable automatic software updates on my iPad?", False),
        ("Storage full error prevents downloading the new software patch.", False),
        ("My keyboard lagging severely while typing after latest update.", False),
        ("Control center missing toggles after updating my device.", False),
        ("Unable to verify update error message pops up constantly.", False),
        ("My wallpaper resets to default black screen after restarting.", False),
        ("How do I update my Apple Watch software from my iPhone?", False),
        ("Apps close automatically right after opening them on iOS 17.", False),
        ("Notification sounds are muted after updating to silent mode bug.", False),
        ("Safari browser loading web pages extremely slow post update.", False),
        ("Is it safe to update my old iPhone 11 to the new iOS version?", False),
        ("Phone screen unresponsive after software update reboot.", True),
        ("How to clear cached system update files to free up internal storage?", False),
        ("Widgets on home screen are blank and not refreshing data.", False),
        ("AirDrop failing to transfer files to other devices after update.", False)
    ],
    "connectivity_sync": [
        ("My iCloud photos stopped syncing to my Windows PC app after yesterday's update.", False),
        ("Bluetooth keeps disconnecting from car dashboard every 5 minutes.", False),
        ("AirPods Pro won't connect to my Mac after updating macOS.", False),
        ("Wi-Fi button is grayed out in Settings and cannot be turned on.", True),
        ("Personal Hotspot drops connection as soon as screen locks.", False),
        ("iCloud Drive files are not downloading on my iPad.", False),
        ("Cellular data network not working showing 'No Service' error.", True),
        ("AirDrop is not discovering nearby devices even when turned on.", False),
        ("My Apple Watch is not syncing health and fitness data to iPhone.", False),
        ("MacBook cannot connect to 5GHz Wi-Fi network band.", False),
        ("Continuity camera not working between iPhone and Mac.", False),
        ("Screen Mirroring to AirPlay smart TV keeps buffering.", False),
        ("My contacts are not syncing between my iPhone and iPad via iCloud.", False),
        ("CarPlay disconnects whenever I move my lightning cable.", False),
        ("Bluetooth devices list takes too long to populate nearby devices.", False),
        ("iMessage turns green and fails to send over Wi-Fi network.", False),
        ("eSIM activation failed with error 'SIM not supported'.", True),
        ("iCloud backup fails every night with 'not enough space' error.", False),
        ("HandOff feature stopped working between Mac and iPhone.", False),
        ("My iPad loses Wi-Fi connection whenever I move to another room.", False),
        ("Universal Control cursor gets stuck between screens.", False),
        ("GPS location accuracy is inaccurate in Navigation apps.", False),
        ("AirPods disconnect automatically during phone call after 2 mins.", False),
        ("HomeKit smart accessories showing 'No Response' status.", False),
        ("Cannot share Wi-Fi password popup not appearing.", False)
    ],
    "general_query": [
        ("What are the trade-in values for an Apple Watch Series 6?", False),
        ("What time does the Apple Store in Regent Street open today?", False),
        ("Where can I check if Apple services like iCloud or iMessage are down?", False),
        ("How long does standard delivery take for an online Apple order?", False),
        ("Can I return an open-box Mac bought at an Apple Store within 14 days?", False),
        ("Does Apple offer student discounts on MacBook Air purchases?", False),
        ("How do I schedule a Genius Bar appointment at a nearby Apple Store?", False),
        ("What is included inside the box with the new iPhone purchase?", False),
        ("How do I check my Apple gift card digital balance?", False),
        ("Can I trade in a damaged iPhone with a cracked back glass?", False),
        ("Is AppleCare+ transferable if I sell my device to someone else?", False),
        ("What payment options are accepted on the official Apple Store online?", False),
        ("How do I track my shipped package from Apple Online Store?", False),
        ("Does Apple offer military or government employee discounts?", False),
        ("Where can I find authorized Apple service providers near my location?", False),
        ("How does the trade-in process work for mail-in devices?", False),
        ("Can I pick up my online store order at a local physical Apple Store?", False),
        ("What is the return policy for refurbished products bought from Apple?", False),
        ("How do I sign up for free Apple Today sessions at Apple Stores?", False),
        ("Is AppleCare available for purchase after 60 days of buying device?", False),
        ("What recycled materials are used in the manufacturing of new iPhones?", False),
        ("How do I recycle my old electronic devices at an Apple Store?", False),
        ("Can I use multiple gift cards on a single online Apple purchase?", False),
        ("What is the difference between AppleCare and AppleCare+ plans?", False),
        ("Where can I read the official user manual for macOS Sequoia?", False)
    ]
}

golden_samples = []
count = 1

for intent, items in categories_data.items():
    for text, escalate in items:
        golden_samples.append({
            "id": f"gold_{count:03d}",
            "customer_tweet": f"@AppleSupport {text}",
            "gold_intent": intent,
            "gold_escalate": escalate,
            "escalation_reason": "Financial transaction dispute or complex account security issue" if escalate else None
        })
        count += 1

with open("golden_set.json", "w", encoding="utf-8") as f:
    json.dump(golden_samples, f, indent=2)

print(f"Successfully generated golden_set.json with EXACTLY {len(golden_samples)} unique hand-labelled test cases!")